# curl -X POST http://192.168.11.45:7001/delete-wa-message
#  -H "Content-Type: application/json"
#  -H "x-api-token: your-generated-token"
#  -d '{"conversation_id": 1095, "cw_message_id": 51191, "source_id": "true_27153387237439@lid_3EB0EAD506FF5"}'
POST http://192.168.11.45:7001/delete-wa-message
x-api-token: your-generated-token
Content-Type: application/json

{"conversation_id": 1095, "cw_message_id": 51191, "source_id": "true_27153387237439@lid_3EB0EAD506FF5"}

###



[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD {
  event: 'conversation_typing_on',
  hasMessage: false,
  hasConversation: true
}
[CW_WEBHOOK] SKIP { reason: 'unhandled event', event: 'conversation_typing_on' }
POST /chatwoot/webhook?token=your-generated-token 200 0.681 ms - 39
[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD {
  event: 'conversation_typing_off',
  hasMessage: false,
  hasConversation: true
}
[CW_WEBHOOK] SKIP { reason: 'unhandled event', event: 'conversation_typing_off' }
POST /chatwoot/webhook?token=your-generated-token 200 0.585 ms - 39
[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD { event: 'message_created', hasMessage: true, hasConversation: true }
[CW_WEBHOOK] PAYLOAD { event: 'message_created', hasMessage: true, hasConversation: true }
POST /chatwoot/webhook?token=your-generated-token 200 50.482 ms - 11
[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD {
  event: 'conversation_typing_on',
  hasMessage: false,
  hasConversation: true
}
[CW_WEBHOOK] SKIP { reason: 'unhandled event', event: 'conversation_typing_on' }
POST /chatwoot/webhook?token=your-generated-token 200 0.546 ms - 39
[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD {
  event: 'conversation_typing_off',
  hasMessage: false,
  hasConversation: true
}
[CW_WEBHOOK] SKIP { reason: 'unhandled event', event: 'conversation_typing_off' }
POST /chatwoot/webhook?token=your-generated-token 200 0.580 ms - 39
[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD {
  event: 'conversation_typing_on',
  hasMessage: false,
  hasConversation: true
}
[CW_WEBHOOK] SKIP { reason: 'unhandled event', event: 'conversation_typing_on' }
POST /chatwoot/webhook?token=your-generated-token 200 0.513 ms - 39
[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD {
  event: 'conversation_typing_off',
  hasMessage: false,
  hasConversation: true
}
[CW_WEBHOOK] SKIP { reason: 'unhandled event', event: 'conversation_typing_off' }
POST /chatwoot/webhook?token=your-generated-token 200 0.999 ms - 39
[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD {
  event: 'conversation_typing_on',
  hasMessage: false,
  hasConversation: true
}
[CW_WEBHOOK] SKIP { reason: 'unhandled event', event: 'conversation_typing_on' }
POST /chatwoot/webhook?token=your-generated-token 200 0.525 ms - 39
[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD {
  event: 'conversation_typing_off',
  hasMessage: false,
  hasConversation: true
}
[CW_WEBHOOK] SKIP { reason: 'unhandled event', event: 'conversation_typing_off' }
POST /chatwoot/webhook?token=your-generated-token 200 0.514 ms - 39
[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD {
  event: 'conversation_typing_on',
  hasMessage: false,
  hasConversation: true
}
[CW_WEBHOOK] SKIP { reason: 'unhandled event', event: 'conversation_typing_on' }
POST /chatwoot/webhook?token=your-generated-token 200 0.547 ms - 39
[CW_WEBHOOK] TAP {
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  q: { token: 'your-generated-token' }
}
[CW_WEBHOOK] ARRIVE {
  ip: '172.19.0.1',
  method: 'POST',
  ua: 'rest-client/2.1.0 (linux-musl x86_64) ruby/3.4.4p34',
  ct: 'application/json',
  hasToken: true
}
[CW_WEBHOOK] HEAD {
  event: 'conversation_typing_off',
  hasMessage: false,
  hasConversation: true
}
[CW_WEBHOOK] SKIP { reason: 'unhandled event', event: 'conversation_typing_off' }
POST /chatwoot/webhook?token=your-generated-token 200 0.497 ms - 39

